### ISSUE TITLE
phase 0.5 bug

### ISSUE THREAD

**Issue by mzechmeister** [hpparvi/PyTransit#27] opened 2018-12-06 11:39 UTC
An example very similar to the one from the readme, but with `i=90 deg` and over one full orbit
```python
import numpy as np
from pytransit import MandelAgol

p = 1.01
t = np.linspace(4-p/2, 4.+p/2, 5000)

k, t0, a, i, e, w = 0.1, 4, 8, 0.5*np.pi, 0.2, 0.5*np.pi
u = [0.25,0.10]

m = MandelAgol()
m.evaluate(t, k, u, t0, p, a, i, e, w)
```
returns
```
array([0.98889585, 1.        , 1.        , ..., 1.        , 1.        ,
       0.98889585])
```
So outliers occur at exactly `t0 +/- P/2`.

**Comment by hpparvi** [comment] 2020-05-25 21:28
Fixed now for QuadraticModel. This was caused by the normalized projected distance (z) reaching a negative zero at the centre of the secondary eclipse (p/2).

**Closed by hpparvi** 2020-05-25 21:28 UTC
Labels: bug
